title: Måns Magnusson
email: exoji2e@gmail.com
description: >-
    My blog, where I write about stuff I find interesting. 
    Including but not limited to; Competitive Programming, Open Source Software, Algorithms and Politics.
baseurl: "" 
url: "https://exoji2e.github.io"
github_username: exoji2e
google_analytics: UA-126799249-1

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed

